//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ofc {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ofc.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid escape sequence &apos;\{0}&apos;.
        /// </summary>
        internal static string LexerErrorInvalidEscapeSequence {
            get {
                return ResourceManager.GetString("LexerErrorInvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected end of stream..
        /// </summary>
        internal static string LexerErrorUnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("LexerErrorUnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected symbol..
        /// </summary>
        internal static string LexerErrorUnexpectedSymbol {
            get {
                return ResourceManager.GetString("LexerErrorUnexpectedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected symbol &apos;{0}&apos;..
        /// </summary>
        internal static string LexerErrorUnexpectedSymbol1 {
            get {
                return ResourceManager.GetString("LexerErrorUnexpectedSymbol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown lexer error..
        /// </summary>
        internal static string LexerErrorUnknown {
            get {
                return ResourceManager.GetString("LexerErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unterminated block comment..
        /// </summary>
        internal static string LexerErrorUnterminatedBlockComment {
            get {
                return ResourceManager.GetString("LexerErrorUnterminatedBlockComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unterminated string container..
        /// </summary>
        internal static string LexerErrorUnterminatedStringContainer {
            get {
                return ResourceManager.GetString("LexerErrorUnterminatedStringContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unterminated string literal..
        /// </summary>
        internal static string LexerErrorUnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("LexerErrorUnterminatedStringLiteral", resourceCulture);
            }
        }
    }
}
